CREATE SEQUENCE PET_SEQ
    MINVALUE 1
    START WITH 1
    INCREMENT BY 1
    CACHE 20
    KEEP;

CREATE TABLE PET_TAB (
    ID INTEGER DEFAULT PET_SEQ.NEXTVAL,
    CATEGORY VARCHAR2(20),
    NAME VARCHAR2(30) NOT NULL,
    PHOTO VARCHAR2(255),
    TAGS VARCHAR2(255) NOT NULL,
    STATUS VARCHAR2(30) NOT NULL,
    CONSTRAINT PET_PK PRIMARY KEY (ID)
) TABLESPACE APP_TBS;

CREATE INDEX PET_TAGS_IDX ON PET_TAB(TAGS);
CREATE INDEX PET_STATUS_IDX ON PET_TAB(STATUS);
CREATE INDEX PET_CATEGORY_IDX ON PET_TAB(CATEGORY);

CREATE OR REPLACE EDITIONING VIEW PET AS
SELECT ID,
       CATEGORY,
       NAME,
       PHOTO,
       TAGS,
       STATUS
FROM   PET_TAB;

INSERT INTO PET (CATEGORY, NAME, TAGS, STATUS) VALUES ('DOG', 'LEMI', 'MALTAN', 'AVAILABLE');
INSERT INTO PET (CATEGORY, NAME, TAGS, STATUS) VALUES ('DOG', 'DAKAR', 'BULDOG', 'AVAILABLE');
INSERT INTO PET (CATEGORY, NAME, TAGS, STATUS) VALUES ('DOG', 'UGO', 'JAMNIK', 'AVAILABLE');
INSERT INTO PET (CATEGORY, NAME, TAGS, STATUS) VALUES ('DOG', 'MESSI', 'MOPS', 'AVAILABLE');
INSERT INTO PET (CATEGORY, NAME, TAGS, STATUS) VALUES ('DOG', 'FIGARTO', 'BEAGLE', 'AVAILABLE');
INSERT INTO PET (CATEGORY, NAME, TAGS, STATUS) VALUES ('DOG', 'PACO', 'MALTAN', 'AVAILABLE');

INSERT INTO PET (CATEGORY, NAME, TAGS, STATUS) VALUES ('CAT', 'NUNIA', 'DACHOWIEC', 'AVAILABLE');
INSERT INTO PET (CATEGORY, NAME, TAGS, STATUS) VALUES ('CAT', 'ATOM', 'PERS', 'AVAILABLE');
INSERT INTO PET (CATEGORY, NAME, TAGS, STATUS) VALUES ('CAT', 'ORION', 'PERS', 'AVAILABLE');
INSERT INTO PET (CATEGORY, NAME, TAGS, STATUS) VALUES ('CAT', 'HERMAN', 'SFINKS', 'AVAILABLE');
INSERT INTO PET (CATEGORY, NAME, TAGS, STATUS) VALUES ('CAT', 'KROPKA', 'SYBERYJSKI', 'AVAILABLE');