--# CREATE EDITION
-- CREATE EDITION V2;
-- ALTER SESSION SET EDITION = V2;

CREATE SEQUENCE CATEGORY_SEQ
    MINVALUE 1
    START WITH 1
    INCREMENT BY 1
    CACHE 20
    KEEP;

CREATE TABLE CATEGORY_TAB (
    ID INTEGER DEFAULT CATEGORY_SEQ.NEXTVAL,
    NAME VARCHAR2(20) NOT NULL,
    CONSTRAINT CATEGORY_PK PRIMARY KEY (ID)
) TABLESPACE APP_TBS;
CREATE INDEX CATEGORY_NAME_IDX ON CATEGORY_TAB(NAME);

ALTER TABLE PET_TAB ADD CATEGORY_ID INTEGER ADD CONSTRAINT PET_CATEGORY_FK FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY_TAB(ID);

CREATE OR REPLACE EDITIONING VIEW CATEGORY AS
SELECT
    ID,
    NAME
FROM CATEGORY_TAB;

INSERT INTO CATEGORY (NAME) SELECT DISTINCT CATEGORY FROM PET_TAB;
UPDATE PET_TAB P SET P.CATEGORY_ID = (SELECT C.ID FROM CATEGORY C WHERE C.NAME = P.CATEGORY);

CREATE OR REPLACE EDITIONING VIEW PET AS
SELECT ID,
       NAME,
       PHOTO,
       TAGS,
       STATUS,
       CATEGORY_ID
FROM   PET_TAB;

CREATE OR REPLACE TRIGGER CATEGORY_FIX_FORWARD_TRG
    BEFORE INSERT OR UPDATE OF CATEGORY ON PET_TAB
    FOR EACH ROW
    FORWARD CROSSEDITION
    DISABLE
DECLARE
    CATEGORY_ID_TMP INTEGER;
BEGIN
    BEGIN
        SELECT ID INTO CATEGORY_ID_TMP FROM CATEGORY_TAB WHERE NAME = UPPER(:NEW.CATEGORY);
        :NEW.CATEGORY_ID := CATEGORY_ID_TMP;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            INSERT INTO CATEGORY_TAB (NAME) VALUES (:NEW.CATEGORY) RETURNING ID INTO CATEGORY_ID_TMP;
            :NEW.CATEGORY_ID := CATEGORY_ID_TMP;
    END;
END;
/
ALTER TRIGGER CATEGORY_FIX_FORWARD_TRG ENABLE;

CREATE OR REPLACE TRIGGER CATEGORY_FIX_REVERSE_TRG
    BEFORE INSERT OR UPDATE OF CATEGORY_ID ON PET_TAB
    FOR EACH ROW
    REVERSE CROSSEDITION
    DISABLE
DECLARE
    CATEGORY_NAME_TMP VARCHAR2(20);
BEGIN
    SELECT NAME INTO CATEGORY_NAME_TMP FROM CATEGORY_TAB WHERE ID = :NEW.CATEGORY_ID;
    :NEW.CATEGORY := CATEGORY_NAME_TMP;
END;
/
ALTER TRIGGER CATEGORY_FIX_REVERSE_TRG ENABLE;

-- ALTER TABLE PET_TAB DROP COLUMN CATEGORY;
